#!/usr/bin/env python3
"""Scan content/ and regenerate js/manifest.js. Run after adding/removing any .md file."""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CONTENT = ROOT / "content"
OUT = ROOT / "js" / "manifest.js"

# Explicit reading order per directory (filename stem, no .md) — alphabetical
# sorting gets several of these wrong (e.g. "a-csm" would sort before "csm").
# Anything found on disk but missing from a list here is appended alphabetically
# at the end, so a new file never silently disappears from the manifest.
ORDER = {
    "00-start-here": ["how-to-use-this-guide", "scrum-master-career-path"],
    "01-agile-foundations": [
        "agile-manifesto", "agile-vs-waterfall",
        "empiricism-and-lean-thinking", "history-of-scrum",
    ],
    "02-scrum-framework": [
        "scrum-values", "scrum-theory-pillars", "scrum-team",
        "sprint", "sprint-planning", "daily-scrum", "sprint-review",
        "sprint-retrospective", "product-backlog", "sprint-backlog",
        "increment", "definition-of-done",
    ],
    "04-scrum-master-role": [
        "servant-leadership", "the-4-sm-service-areas", "facilitation-techniques",
        "coaching-vs-mentoring-vs-teaching", "conflict-resolution",
        "removing-impediments", "shielding-vs-enabling", "metrics-and-forecasting",
        "working-with-difficult-stakeholders", "anti-patterns-and-scrum-smells",
    ],
    "05-scaling-frameworks": [
        "why-and-when-to-scale", "nexus", "scrum-at-scale", "less", "safe-overview",
    ],
    "07-certifications": ["00-which-certification-should-i-get", "comparison-table"],
    "07-certifications/scrum-alliance": ["csm", "a-csm", "csp-sm"],
    "07-certifications/safe": ["safe-scrum-master", "safe-advanced-scrum-master"],
    "08-templates-and-toolkit": [
        "sprint-planning-agenda", "daily-scrum-formats", "retrospective-formats",
        "definition-of-done-checklist", "raci-and-stakeholder-map",
        "one-on-one-question-bank",
    ],
}
# Subgroup (2nd-level folder) order within a parent section, e.g. inside
# 07-certifications: scrum-org before scrum-alliance before safe.
SUBGROUP_ORDER = {
    "07-certifications": ["scrum-org", "scrum-alliance", "safe"],
}


def title_of(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^#\s+(.+)$", line.strip())
        if m:
            return m.group(1).strip()
    return path.stem.replace("-", " ").title()


def ordered_stems(dir_key: str, stems: list) -> list:
    explicit = ORDER.get(dir_key, [])
    rest = sorted(s for s in stems if s not in explicit)
    return [s for s in explicit if s in stems] + rest


def main():
    # top-level section directories, in numeric order
    section_dirs = sorted(
        [p for p in CONTENT.iterdir() if p.is_dir()],
        key=lambda p: p.name,
    )
    root_files = sorted(
        [p for p in CONTENT.iterdir() if p.is_file() and p.suffix == ".md"],
        key=lambda p: p.name,
    )

    manifest = []

    for sect in section_dirs:
        subdirs = sorted([p for p in sect.iterdir() if p.is_dir()])
        direct_md = [p for p in sect.iterdir() if p.is_file() and p.suffix == ".md"]

        direct_stems = [p.stem for p in direct_md]
        for stem in ordered_stems(sect.name, direct_stems):
            f = sect / f"{stem}.md"
            manifest.append({
                "path": f"{sect.name}/{stem}.md",
                "title": title_of(f),
            })

        sub_order = SUBGROUP_ORDER.get(sect.name, sorted(d.name for d in subdirs))
        subdirs_by_name = {d.name: d for d in subdirs}
        for sub_name in sub_order:
            d = subdirs_by_name.get(sub_name)
            if not d:
                continue
            md_files = [p for p in d.iterdir() if p.suffix == ".md"]
            stems = [p.stem for p in md_files]
            key = f"{sect.name}/{sub_name}"
            for stem in ordered_stems(key, stems):
                f = d / f"{stem}.md"
                manifest.append({
                    "path": f"{sect.name}/{sub_name}/{stem}.md",
                    "title": title_of(f),
                })
        # catch any subdir not covered by sub_order (safety net)
        for name, d in subdirs_by_name.items():
            if name not in sub_order:
                md_files = sorted(p for p in d.iterdir() if p.suffix == ".md")
                for f in md_files:
                    manifest.append({
                        "path": f"{sect.name}/{d.name}/{f.stem}.md",
                        "title": title_of(f),
                    })

    for f in root_files:
        manifest.append({"path": f.name, "title": title_of(f)})

    OUT.write_text(
        "// Auto-generated by tools/build_manifest.py — do not hand-edit.\n"
        "const MANIFEST = " + json.dumps(manifest, indent=2, ensure_ascii=False) + ";\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(manifest)} entries to {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
